config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_cart' => 'cart#view_order'

  post 'checkout' => 'cart#checkout'

  resources :orders

  resources :line_items

  devise_for :users
  
  root 'storefront#all_items'

  get 'storefront/items_by_category'

  get 'storefront/items_by_brand'

  get 'products' => 'products#index'
  get 'categories' => 'categories#index'

  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :categories

  resources :products

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
     	<li><%= link_to "Categories", categories_path %></li>
        <li><%= link_to "Products", products_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Find By Category <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          	<% Category.all.each do | cat | %>
          		<li><%= link_to cat.name, categorical_path(cat_id: cat.id) %></li>
          	<%end%>
          </ul>
        </li>
         <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Find By Brand<span class="caret"></span></a>
	        <ul class = 'dropdown-menu' role = 'menu'>
	            <% @brands.each do |brand| %>
	            <li><%=link_to brand, branding_path(brand: brand)%></li>
	            <% end %>
	        </ul>
        </li>       
          <li>
		      <% if user_signed_in? %>
		        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-success" %>
		      <% end %>
		  </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
<%= yield %>
</div>

</body>
</html>